name: Code Coverage

on:
   merge:
      branches: [main, dev]
      
jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: 11
          architecture: 'x64'

      - name: Code Coverage
        run:|
            chmod +x gradlew
            ./gradlew jacocoTestReport
        shell: bash
        uses: coverallsapp/github-action@v1.1.2
        with:
        github-token: ${{ github.token }}
