name: Code Coverage

on:
   push:
      branches: [main, dev]
env:
  # TODO: Change variable to your image's name.
  COVERALLS_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
         
jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: 11
          architecture: 'x64'

      - name: Code Coverage
        run: |
             chmod +x gradlew
             ./gradlew build jacocoTestReport
             ./gradlew coveralls
        shell: bash
         
