name: Changelog

on:
   push:
      branches: [main, dev]
      
- name: "Build Changelog"
  id: build_changelog
  uses: mikepenz/release-changelog-builder-action@{latest-release}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  steps:
      - name: Display version
        run: |
          echo Changelog: ${{steps.build_changelog.outputs.changelog}}
