name: Changelog

on:
   push:
      branches: [main, dev]

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
         - uses: mikepenz/release-changelog-builder-action@{latest-release}

         - name: "Build Changelog"
           run: |
                echo Changelog: ${{steps.build_changelog.outputs.changelog}}
